__author__ = 'loolroco'
WORK_FOLD = '/home/www/SMI-BLAST/webserver'
MODEL_FOLD = '/home/www/SMI-BLAST/webserver/model'
USER_FOLD = '/home/www/SMI-BLAST/webserver/temp/user'
PASSWORD = 'bionlp2017'
CON_FOLD='/home/www/SMI-BLAST'
# UPLOADFOLD = 'webserver/temp/upload'
COMMAND = 'bash /home/www/SMI-BLAST/webserver/model/code/run.sh '
MAX_NUM_OF_SEQUENCES = 10
ALPHABET = {'A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y'}
